name: Update Data

on:
  schedule:
    - cron: "0 0 15 * *"  # Run every 15th of the month
  workflow_dispatch:  # Allow manual trigger

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest

    steps:
    #step1 checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: true  # Ensures GITHUB_TOKEN is used for push

    #step2 set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Use a compatible Python version

    #step 3 install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    #step4 grab and process BLS data
    - name: Grab and process BLS data
      run: python grab_and_process_data.py

    #step 5 commit and push changes
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add bls_data.csv
        git commit -m "Update BLS data (automated)" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
